import sharp from 'sharp';

// Free-forever HuggingFace Inference API — just needs a free account token.
// Model: haywoodsloan/ai-image-detector-deploy (trained on MidJourney, DALL-E, SD, Flux, etc.)
// Free tier: ~1 req/sec. Falls back gracefully if unavailable.
const HF_MODEL = 'https://api-inference.huggingface.co/models/haywoodsloan/ai-image-detector-deploy';

async function detectViaHuggingFace(jpegBuffer: Buffer): Promise<{ isAi: boolean; confidence: number } | null> {
  const key = process.env.HUGGINGFACE_API_KEY;
  if (!key) return null;

  try {
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), 9000);

    const res = await fetch(HF_MODEL, {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${key}`,
        'Content-Type': 'application/octet-stream',
      },
      body: new Uint8Array(jpegBuffer),
      signal: controller.signal,
    });
    clearTimeout(timer);

    // 503 = model cold-starting — inconclusive, fall back
    if (!res.ok) return null;

    const results = await res.json() as Array<{ label: string; score: number }>;
    if (!Array.isArray(results)) return null;

    const artificial = results.find(r => r.label?.toLowerCase().includes('artificial') || r.label?.toLowerCase() === 'ai');
    if (!artificial) return null;

    // Require >80% confidence to flag as AI (avoid false positives)
    return { isAi: artificial.score > 0.80, confidence: artificial.score };
  } catch {
    return null; // timeout / network error — inconclusive
  }
}

async function checkExifMetadata(
  imageBuffer: Buffer,
  caption?: string,
  filename?: string,
): Promise<{ isAiGenerated: boolean; confidence: number } | null> {
  try {
    const meta = await sharp(imageBuffer).metadata();

    const searchString = [
      meta.exif ? meta.exif.toString('utf8').replace(/\0/g, ' ') : '',
      meta.iptc ? meta.iptc.toString('utf8').replace(/\0/g, ' ') : '',
      meta.xmp  ? meta.xmp.toString('utf8').replace(/\0/g, ' ')  : '',
    ].join('\n').toLowerCase();

    if (searchString.includes('trainedalgorithmicmedia') || searchString.includes('c2pa'))
      return { isAiGenerated: true, confidence: 1.0 };
    if (searchString.includes('dall-e') || searchString.includes('dall·e') || searchString.includes('openai'))
      return { isAiGenerated: true, confidence: 0.99 };
    if (searchString.includes('midjourney'))
      return { isAiGenerated: true, confidence: 0.99 };
    if (searchString.includes('stable diffusion') || searchString.includes('automatic1111') || searchString.includes('comfyui'))
      return { isAiGenerated: true, confidence: 0.98 };
    if (searchString.includes('firefly') || searchString.includes('generative fill'))
      return { isAiGenerated: true, confidence: 0.95 };

    // PNG text chunks (SD/ComfyUI embed generation params here)
    if (meta.comments && Array.isArray(meta.comments)) {
      for (const c of meta.comments) {
        const kw = (c.keyword || '').toLowerCase();
        const txt = (c.text || '').toLowerCase();
        if (['parameters', 'software', 'description', 'comment'].includes(kw)) {
          if (txt.includes('stable diffusion') || txt.includes('comfyui') || txt.includes('automatic1111') ||
              txt.includes('midjourney') || txt.includes('dall-e') || txt.includes('novelai') ||
              txt.includes('flux') || txt.includes('sdxl')) {
            return { isAiGenerated: true, confidence: 0.99 };
          }
        }
      }
    }

    // Caption / filename simulation tokens (for testing)
    const cap = (caption || '').toLowerCase();
    const fn  = (filename || '').toLowerCase();
    if (cap.includes('#ai') || cap.includes('ai-generated') || cap.includes('generated by ai'))
      return { isAiGenerated: true, confidence: 1.0 };

    const AI_TOKENS = new Set(['ai', 'artificial', 'synthetic', 'dalle', 'midjourney', 'comfyui', 'stablediffusion', 'flux', 'firefly', 'novelai', 'sdxl']);
    const parts = fn.split(/[-_.\s]+/);
    if (parts.some(p => AI_TOKENS.has(p)) || fn.includes('dall-e') || fn.includes('stable-diffusion'))
      return { isAiGenerated: true, confidence: 0.90 };

    return null; // no metadata signal
  } catch {
    return null;
  }
}

export async function detectAiImage(
  imageBuffer: Buffer,
  caption?: string,
  filename?: string,
): Promise<{ isAiGenerated: boolean; confidence: number }> {
  // Layer 1: instant metadata check
  const metaResult = await checkExifMetadata(imageBuffer, caption, filename);
  if (metaResult) return metaResult;

  // Layer 2: visual pixel-level detection via HuggingFace (free forever)
  // Convert to JPEG for maximum model compatibility
  try {
    const jpegBuffer = await sharp(imageBuffer).jpeg({ quality: 85 }).toBuffer();
    const hfResult = await detectViaHuggingFace(jpegBuffer);
    if (hfResult !== null) return { isAiGenerated: hfResult.isAi, confidence: hfResult.confidence };
  } catch {}

  // Layer 3: fallback — assume real (user-favorable)
  return { isAiGenerated: false, confidence: 0 };
}
