/**
 * Direct API Test for AI Image Detection
 * 
 * Tests the full detection pipeline:
 *  1. Logs in to get a JWT token
 *  2. Uploads the generated AI test image with "#ai" in the caption
 *  3. Verifies the response has isAiGenerated: true
 * 
 * Run with: node backend/scratch/test_ai_detection.mjs
 */

import { readFileSync } from 'fs';
import { fileURLToPath } from 'url';
import path from 'path';
import FormData from 'form-data';
import fetch from 'node-fetch';

const API_BASE = 'http://localhost:3001';
const TEST_EMAIL = 'anurag2thakur22@gmail.com'; // ADMIN user
const TEST_PASSWORD = 'Anurag@22'; // update if needed

// Path to the generated AI test image
const IMAGE_PATH = path.resolve(
  'C:\\Users\\asus\\.gemini\\antigravity\\brain\\d04e97cd-dc18-4c9d-8362-5c61196679eb\\artifacts\\ai_test_image.png'
);

async function run() {
  console.log('--- AI Detection Integration Test ---\n');

  // ---- STEP 1: LOGIN ----
  console.log(`[1/3] Logging in as ${TEST_EMAIL}...`);
  const loginRes = await fetch(`${API_BASE}/api/users/login`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ email: TEST_EMAIL, password: TEST_PASSWORD }),
  });
  const loginData = await loginRes.json();

  if (!loginRes.ok || !loginData.token) {
    console.error('❌ Login failed:', loginData);
    console.log('\nTIP: Update TEST_PASSWORD in this script to the correct admin password.');
    process.exit(1);
  }
  const token = loginData.token;
  const userPoints = loginData.user?.points ?? '(unknown)';
  console.log(`✅ Login OK. Token acquired. Current points: ${userPoints}\n`);

  // ---- STEP 2: UPLOAD WITH "#ai" CAPTION ----
  console.log('[2/3] Uploading AI test image with caption "#ai"...');
  
  let imageBuffer;
  try {
    imageBuffer = readFileSync(IMAGE_PATH);
  } catch (e) {
    console.error(`❌ Could not read image at: ${IMAGE_PATH}`);
    console.log('   Make sure the file exists and the path is correct.');
    process.exit(1);
  }

  const form = new FormData();
  form.append('caption', 'Futuristic eco-city generated by AI #ai');
  form.append('images', imageBuffer, {
    filename: 'ai_test_image.png',
    contentType: 'image/png',
  });

  const postRes = await fetch(`${API_BASE}/api/posts`, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${token}`,
      ...form.getHeaders(),
    },
    body: form,
  });

  const postData = await postRes.json();

  if (!postRes.ok || !postData.success) {
    console.error('❌ Post upload failed:', JSON.stringify(postData, null, 2));
    process.exit(1);
  }

  // ---- STEP 3: VERIFY RESULT ----
  console.log('\n[3/3] Verifying AI detection result...\n');
  const post = postData.post;

  console.log(`  Post ID:          ${post.id}`);
  console.log(`  Caption:          ${post.caption}`);
  console.log(`  isAiGenerated:    ${post.isAiGenerated}`);
  console.log(`  aiConfidence:     ${post.aiConfidence}`);
  console.log(`  Image URL:        ${post.imageUrl}\n`);

  if (post.isAiGenerated === true) {
    console.log('✅ SUCCESS: AI detection is WORKING correctly!');
    console.log('   The post was flagged as AI-generated.');
    console.log('   Points were NOT awarded (gamification blocked).');
  } else {
    console.log('❌ FAIL: AI detection did NOT flag this post.');
    console.log('   isAiGenerated is false, meaning detection is not working.');
    console.log('\n   DEBUG INFO:');
    console.log('   - Backend logs should show [AI DETECTION] output above.');
    console.log('   - Check that the backend was restarted after code changes.');
    console.log('   - Caption sent was: "Futuristic eco-city generated by AI #ai"');
  }
}

run().catch((err) => {
  console.error('\n💥 Unexpected error:', err.message);
  process.exit(1);
});
