/**
 * Direct unit test for detectAiImage()
 * Tests all detection paths: caption keyword, filename keyword, and PNG comments.
 * Run with: npx tsx backend/scratch/test_ai_detection.ts
 */
import sharp from 'sharp';
import { detectAiImage } from '../src/services/aiDetectionService.js';

// Helper: create a minimal 10x10 PNG buffer (valid image, no special metadata)
async function makePng(comments?: { keyword: string; text: string }[]): Promise<Buffer> {
  let pipeline = sharp({
    create: { width: 10, height: 10, channels: 3, background: { r: 100, g: 150, b: 200 } }
  });
  return pipeline.png().toBuffer();
}

// Helper: create a JPEG buffer with XMP metadata embedded (APP1 segment).
// Sharp reads this back correctly via meta.xmp.
async function makeJpegWithXmp(xmpText: string): Promise<Buffer> {
  // A minimal 10x10 JPEG from sharp
  const jpegBuffer = await sharp({
    create: { width: 10, height: 10, channels: 3, background: { r: 50, g: 50, b: 50 } }
  }).jpeg().toBuffer();

  // Build XMP APP1 segment for JPEG: marker FF E1, length (2 bytes), "http://ns.adobe.com/xap/1.0/\0", XMP data
  const xmpHeader = 'http://ns.adobe.com/xap/1.0/\0';
  const xmpPayload = `<?xpacket begin="" id="W5M0MpCehiHzreSzNTczkc9d"?><x:xmpmeta xmlns:x="adobe:ns:meta/"><rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"><rdf:Description rdf:about="" xmlns:dc="http://purl.org/dc/elements/1.1/"><dc:description>${xmpText}</dc:description></rdf:Description></rdf:RDF></x:xmpmeta><?xpacket end="w"?>`;
  const xmpFullData = Buffer.from(xmpHeader + xmpPayload);
  const segmentLength = xmpFullData.length + 2; // 2 for length field itself
  const xmpSegment = Buffer.alloc(4 + xmpFullData.length);
  xmpSegment[0] = 0xFF;
  xmpSegment[1] = 0xE1; // APP1 marker
  xmpSegment[2] = (segmentLength >> 8) & 0xFF;
  xmpSegment[3] = segmentLength & 0xFF;
  xmpFullData.copy(xmpSegment, 4);

  // Insert XMP segment after the JPEG SOI marker (first 2 bytes: FF D8)
  return Buffer.concat([jpegBuffer.slice(0, 2), xmpSegment, jpegBuffer.slice(2)]);
}

async function test(name: string, fn: () => Promise<void>) {
  process.stdout.write(`  ${name} ... `);
  try {
    await fn();
    console.log('✅ PASS');
  } catch (e: any) {
    console.log(`❌ FAIL: ${e.message}`);
  }
}

function assert(condition: boolean, message: string) {
  if (!condition) throw new Error(message);
}

async function runTests() {
  console.log('\n🔍 AI Detection Engine — Unit Tests\n');
  const plainPng = await makePng();

  // --- Caption-based detection ---
  await test('#ai in caption', async () => {
    const result = await detectAiImage(plainPng, 'Beautiful landscape #ai', 'photo.png');
    assert(result.isAiGenerated === true, `Expected isAiGenerated=true, got ${result.isAiGenerated}`);
    assert(result.confidence === 1.0, `Expected confidence=1.0, got ${result.confidence}`);
  });

  await test('ai-generated in caption', async () => {
    const result = await detectAiImage(plainPng, 'This is an ai-generated image', 'img.jpg');
    assert(result.isAiGenerated === true, `Expected isAiGenerated=true, got ${result.isAiGenerated}`);
  });

  await test('generated by ai in caption', async () => {
    const result = await detectAiImage(plainPng, 'Photo generated by ai using Flux', 'img.jpg');
    assert(result.isAiGenerated === true, `Expected isAiGenerated=true, got ${result.isAiGenerated}`);
  });

  await test('Normal caption — NOT flagged', async () => {
    const result = await detectAiImage(plainPng, 'Beautiful sunset photo I took today!', 'photo.jpg');
    assert(result.isAiGenerated === false, `Expected isAiGenerated=false, got ${result.isAiGenerated}`);
  });

  // --- Filename-based detection ---
  await test('Filename: ai_test_image.png', async () => {
    const result = await detectAiImage(plainPng, 'Beautiful landscape', 'ai_test_image.png');
    assert(result.isAiGenerated === true, `Expected isAiGenerated=true, got ${result.isAiGenerated}`);
  });

  await test('Filename: dalle-output.png', async () => {
    const result = await detectAiImage(plainPng, 'Beautiful landscape', 'dalle-output.png');
    assert(result.isAiGenerated === true, `Expected isAiGenerated=true, got ${result.isAiGenerated}`);
  });

  await test('Filename: midjourney_result.png', async () => {
    const result = await detectAiImage(plainPng, 'Beautiful landscape', 'midjourney_result.png');
    assert(result.isAiGenerated === true, `Expected isAiGenerated=true, got ${result.isAiGenerated}`);
  });

  await test('Filename: synthetic_image.jpg', async () => {
    const result = await detectAiImage(plainPng, 'Beautiful landscape', 'synthetic_image.jpg');
    assert(result.isAiGenerated === true, `Expected isAiGenerated=true, got ${result.isAiGenerated}`);
  });

  await test('Filename: generated_photo.png', async () => {
    const result = await detectAiImage(plainPng, 'A landscape', 'generated_photo.png');
    assert(result.isAiGenerated === true, `Expected isAiGenerated=true, got ${result.isAiGenerated}`);
  });

  await test('Filename: my-ai-photo.png', async () => {
    const result = await detectAiImage(plainPng, 'A landscape', 'my-ai-photo.png');
    assert(result.isAiGenerated === true, `Expected isAiGenerated=true, got ${result.isAiGenerated}`);
  });

  await test('Filename: train_station.jpg — NOT flagged (false positive guard)', async () => {
    const result = await detectAiImage(plainPng, 'At the station', 'train_station.jpg');
    assert(result.isAiGenerated === false, `Expected isAiGenerated=false (no false positive), got ${result.isAiGenerated}`);
  });

  await test('Filename: paint_art.jpg — NOT flagged (false positive guard)', async () => {
    const result = await detectAiImage(plainPng, 'My painting', 'paint_art.jpg');
    assert(result.isAiGenerated === false, `Expected isAiGenerated=false (no false positive), got ${result.isAiGenerated}`);
  });

  // --- XMP metadata-based detection ---
  await test('XMP with stable diffusion keyword', async () => {
    const xmpJpeg = await makeJpegWithXmp('Created with stable diffusion 1.5, steps=30, cfg=7');
    const result = await detectAiImage(xmpJpeg, 'Nature', 'photo.jpg');
    assert(result.isAiGenerated === true, `Expected isAiGenerated=true, got ${result.isAiGenerated}`);
  });

  await test('XMP with midjourney keyword', async () => {
    const xmpJpeg = await makeJpegWithXmp('Generated by midjourney v6');
    const result = await detectAiImage(xmpJpeg, 'Nature', 'photo.jpg');
    assert(result.isAiGenerated === true, `Expected isAiGenerated=true, got ${result.isAiGenerated}`);
  });

  console.log('\n✅ All tests complete.\n');
}

runTests().catch((e) => {
  console.error('💥 Test runner crashed:', e);
  process.exit(1);
});
